name: docs

on:
  push:
    branches: [ develop ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3.0.11
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build docs with Maven
        run: mvn clean javadoc:aggregate -DskipTests

      - name: Copy to Documentation Website Location
        run: |
          rm -rf docs
          cp -rf target/site/apidocs/. docs
